export default [
  {
    icon: "mdi-bulletin-board",
    key: "menu.board",
    text: "Board",
    link: "/apps/board",
  },
  {
    icon: "mdi mdi-ladybug",
    key: "menu.creeper_library",
    text: "Creeper Library",
    link: "/apps/creeperLibrary",
    plugin: "CreeperManager",
  },
  {
    icon: "mdi mdi-account-hard-hat-outline",
    key: "menu.task_center",
    text: "Task Center",
    link: "/apps/taskCenter",
    plugin: "TaskCenter",
  },
  {
    icon: "mdi mdi-monitor-cellphone-star",
    key: "menu.hot_guard",
    text: "Hot Guard",
    link: "/apps/hotGuard",
    plugin: "HotGuard",
  },
  {
    icon: "mdi mdi-bird",
    key: "menu.heat_recommend",
    text: "Heat Recommend",
    link: "/apps/heatRecommend",
    plugin: "HotRecommendation",
  },
  {
    icon: "mdi mdi-star-face",
    key: "menu.live_follow",
    text: "Live Follow",
    link: "/apps/liveFollow",
    plugin: "LiverFollower",
  },
  {
    icon: "mdi mdi-chart-line",
    key: "menu.barrage_curve",
    text: "Barrage Curve",
    link: "/apps/barrageCurve",
    plugin: "BarrageScoreCurve",
  },
  {
    icon: "mdi mdi-tag-faces",
    key: "menu.label",
    text: "Label Manage",
    link: "/apps/label",
    plugin: "LabelManager",
  },
  {
    icon: "mdi-forum-outline",
    key: "menu.chat",
    text: "Chat",
    link: "/apps/chat",
  },
  {
    icon: "mdi-format-list-checkbox",
    key: "menu.todo",
    text: "Todo",
    link: "/apps/todo",
  },
  // {
  //   icon: "mdi-bookmark-plus",
  //   key: "menu.nitori",
  //   text: "Nitori",
  //   link: "/apps/nitori",
  // },
  // {
  //   icon: "mdi-bookmark-plus",
  //   key: "menu.booking",
  //   text: "Booking",
  //   link: "/apps/booking",
  // },
  // {
  //   icon: "mdi-bookmark-plus",
  //   key: "menu.ikea",
  //   text: "Ikea",
  //   link: "/apps/ikea",
  // },
  {
    icon: "mdi-bookmark-plus",
    key: "menu.unsplash",
    text: "Unsplash",
    link: "/apps/unsplash",
  },
  {
    icon: "mdi-email-outline",
    key: "menu.email",
    text: "Email",
    link: "/apps/email",
  },
];
