export default [
  {
    icon: "mdi-dots-hexagon",
    key: "menu.heroPage",
    text: "Hero Page",
    link: "/landing/hero",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.featurePage",
    text: "Feature Page",
    link: "/landing/feature",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.pricingPage",
    text: "Pricing Page",
    link: "/landing/pricing",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.cardPage",
    text: "Card Page",
    link: "/landing/card",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.teamPage",
    text: "Team Page",
    link: "/landing/team",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.testimonialPage",
    text: "Testimonial Page",
    link: "/landing/testimonial",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.statsPage",
    text: "Stats Page",
    link: "/landing/stats",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.logosPage",
    text: "Logos Page",
    link: "/landing/logos",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.callToActionPage",
    text: "Call To Action Page",
    link: "/landing/calltoaction",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.newsletterPage",
    text: "Newsletter Page",
    link: "/landing/newsletter",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.faqPage",
    text: "FAQ Page",
    link: "/landing/faq",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.toolbarPage",
    text: "Toolbar Page",
    link: "/landing/toolbar",
  },
  {
    icon: "mdi-dots-hexagon",
    key: "menu.footerPage",
    text: "Footer Page",
    link: "/landing/footer",
  },
];
